### ISSUE TITLE
主节点挖矿至600块时报错

### ISSUE THREAD

**Issue by Dolantinlist** [EdgeIntelligenceChain/EdgenceChain#11]
[2019-01-09 18:13:02,750][edgencechain:489] INFO saving chain with 600 blocks
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/dolantin/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/dolantin/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "edgencechain.py", line 665, in mine_forever
    block = assemble_and_solve_block(my_address)
  File "edgencechain.py", line 582, in assemble_and_solve_block
    bits=get_next_work_required(prev_block_hash),
  File "edgencechain.py", line 556, in get_next_work_required
    prev_height - (Params.DIFFICULTY_PERIOD_IN_BLOCKS - 1), 0)]
TypeError: list indices must be integers or slices, not float

**Comment by wolfbrother** [comment]
出错位置的代码块为：
```
with chain_lock:
        # #realname CalculateNextWorkRequired
        period_start_block = active_chain[max(
            prev_height - (Params.DIFFICULTY_PERIOD_IN_BLOCKS - 1), 0)]  #找到上一个难度的初始区
```

每隔Params.DIFFICULTY_PERIOD_IN_BLOCKS（600）个块，需要调整一下挖矿难度值，此时上述代码块才被执行。

上述代码之所以出错，是因为Params.DIFFICULTY_PERIOD_IN_BLOCKS的值本身是由两个整数直接相除得到的商值，在Python里默认的商值是float类型，而非int。因此会有出错。

修正建议：

类型转换操作，将float类型强行转换为int型。将出错代码块修改为：

```
with chain_lock:
        # #realname CalculateNextWorkRequired
        period_start_block = active_chain[max(
            int(prev_height - (Params.DIFFICULTY_PERIOD_IN_BLOCKS - 1)), 0)]  #找到上一个难度的初始区
```
