### ISSUE TITLE
模块的循环调用测试及总结

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#35]

**Comment by wolfbrother** [comment]
## 使用基类
```
class Teacher(object):
    def __init__(self, age=12):
        self.age = age
        self.students: Iterable[Student] = []
    def addStudent(self, student):
        self.students.append(student)
    def printStudent(self):
        for student in self.students:
            print(student.name)
    
class Student(object):
    def __init__(self, name='Jim'):
        self.name: str = name
        self.teachers: Iterable[object] = []
    def addTeacher(self,teacher):
        self.teachers.append(teacher)
    def printTeacher(self):
        for teacher in self.teachers:
            print(teacher.age)
```

> teacher1 = Teacher(45)
teacher2 = Teacher(46)
student1 = Student('Jim')


> teacher1.addStudent(student1)
student1.addTeacher(teacher1)
student1.addTeacher(teacher2)

> student1.printTeacher()
teacher1.printStudent()

**Comment by wolfbrother** [comment]
## Teacher.py
```
from student.Student import Student

class Teacher(object):
    def __init__(self, age=12):
        self.age = age
        self.students: Iterable[Student] = []
    def addStudent(self, student):
        self.students.append(student)
    def printStudent(self):
        for student in self.students:
            print(student.name)
```

## Student.py
```
import teacher

class Student(object):
    def __init__(self, name='Jim'):
        self.name: str = name
        self.teachers: Iterable[teacher.Teacher.Teacher] = []
    def addTeacher(self,teacher):
        self.teachers.append(teacher)
    def printTeacher(self):
        for teacher in self.teachers:
            print(teacher.age)
```

## main.py
```
from student.Student import Student

from teacher.Teacher import Teacher

teacher1 = Teacher(45)
teacher2 = Teacher(46)
student1 = Student('Jim')

teacher1.addStudent(student1)
student1.addTeacher(teacher1)
student1.addTeacher(teacher2)

student1.printTeacher()
teacher1.printStudent()
```

**Comment by wolfbrother** [comment]
## Teacher.py
```
from student.Student import Student

class Teacher(object):
    def __init__(self, age=12):
        self.age = age
        self.students: Iterable[Student] = []
    def addStudent(self, student):
        self.students.append(student)
    def printStudent(self):
        for student in self.students:
            print(student.name)
```

## Student.py
```
class Student(object):

    def __init__(self, name='Jim'):
        from teacher.Teacher import Teacher
        self.name: str = name
        self.teachers: Iterable[Teacher] = []
    def addTeacher(self, teacher):
        self.teachers.append(teacher)
    def printTeacher(self):
        for teacher in self.teachers:
            print(teacher.age)
```

**Comment by wolfbrother** [comment]
导入的实质
导入其实是要将 被导入模块所有的顶格代码都执行一遍，遇到函数和类的定义会作申明。
如果b模块中有这么一句

> print 'bbb'

你在a模块impot b时就会 执行 print 'bbb'这一句。

**Comment by wolfbrother** [comment]
# 两个互相调用的类都只引入对方的模块，而非具体到类

## Teacher.py
```
from student import Student

class Teacher(object):
    def __init__(self, age=12):
        self.age = age
        self.students: Iterable[Student.Student] = []
    def addStudent(self, student):
        self.students.append(student)
    def printStudent(self):
        for student in self.students:
            print(student.name)
```

## Student.py
```
from teacher import Teacher


class Student(object):
    def __init__(self, name='Jim'):
        self.name: str = name
        self.teachers: Iterable[Teacher.Teacher] = []
    def addTeacher(self, teacher):
        self.teachers.append(teacher)
    def printTeacher(self):
        for teacher in self.teachers:
            print(teacher.age)
```

**Comment by wolfbrother** [comment]
## Teacher.py
```
from student import Student

class Teacher(object):
    def __init__(self, age=12):
        self.age = age
        self.students: Iterable[Student.Student] = []
        self.students.append(Student.Student())
    def addStudent(self, student: Student.Student):
        self.students.append(student)
    def printStudent(self):
        for student in self.students:
            print(student.name)
```

## Student.py
```
from teacher import Teacher


class Student(object):
    def __init__(self, name='Jim'):
        self.name: str = name
        self.teachers: Iterable[Teacher.Teacher] = []
    def addTeacher(self, teacher: Teacher.Teacher):
        self.teachers.append(Teacher.Teacher())
        self.teachers.append(teacher)
    def printTeacher(self):
        for teacher in self.teachers:
            print(teacher.age)
```

> C:\Users\Jin\Desktop\test>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from student import Student
  File "C:\Users\Jin\Desktop\test\student\Student.py", line 1, in <module>
    from teacher import Teacher
  File "C:\Users\Jin\Desktop\test\teacher\Teacher.py", line 3, in <module>
    class Teacher(object):
  File "C:\Users\Jin\Desktop\test\teacher\Teacher.py", line 8, in Teacher
    def addStudent(self, student: Student.Student):
AttributeError: module 'student.Student' has no attribute 'Student'
