### ISSUE TITLE
多次创建连接失败，节点仍未被从列表里剔除

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#45]
情况如下：
```
[2019-01-28 15:40:51,715][Utils:109] ERROR [utils] failed to send to Peer(ip='127.0.0.1', port=9998) data in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/NODE1/utils/Utils.py", line 106, in send_to_peer
    with socket.create_connection(peer(), timeout=1) as s:
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

```

原因：
```
                    for _peer in self.peers:
                        Utils.send_to_peer(Message(Actions.BlockRev, block, Params.PORT_CURRENT), _peer)
                    with self.chain_lock:
```
此处没有对发送结果进行检查。

**Comment by wolfbrother** [comment]
进展如何？你打算怎么解决这个问题？
