### ISSUE TITLE
参考比特币制作脚本引擎

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#55]

**Comment by wolfbrother** [comment]
https://github.com/EdgeIntelligenceChain/Resources4TechDoc/blob/master/20190107-Relations-of-classes/%E5%87%A0%E4%B8%AA%E7%B1%BB%E7%9A%84%E5%85%B3%E7%B3%BB.pdf

**Comment by wolfbrother** [comment]
### 测试 pycoind 程序
  + 源码：  https://github.com/EdgeIntelligenceChain/pycoind
#### 测试任务

+ 示例运行环境 python 2.7

```python
>>>import pycoind
>>>chain = pycoind.blockchain.BlockChain()
>>>block_hash = '6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000'.decode('hex')
>>>print chain.get_block(block_hash)
>>>len(chain)
>>>b = chain[0]
>>>print b
```
+ 测试 tests/test-script.py

**Comment by TemplarJQ** [comment]
### 测试示例
- 如果报错：
```python
>>> chain = pycoind.blockchain.BlockChain()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pycoind/blockchain/__init__.py", line 49, in __init__
    self._blocks = block.Database(data_dir, coin)
  File "pycoind/blockchain/block.py", line 150, in __init__
    self._connection = self.get_connection()
  File "pycoind/blockchain/database.py", line 72, in get_connection
```
解决方法：需要事先安装sqlite，并且默认的sqlite目录在：pycoind/util/__init__.py下设置
```python
def default_data_directory():
    return os.path.expanduser('~/.pycoind/data')
```
没有该目录则创建，即可连接数据库。
### 测试脚本
- 将test-script.py文件放置到pycoind目录下测试结果：
```python
test_binary_math_ops (__main__.TestScriptTransactions) ... ok
test_crypto_ops (__main__.TestScriptTransactions) ... ok
test_flow_control_ops (__main__.TestScriptTransactions) ... ok
test_hashall (__main__.TestScriptTransactions) ... ok
test_hashall_anyonecanpay (__main__.TestScriptTransactions) ... ok
test_hashnone (__main__.TestScriptTransactions) ... ok
test_hashnone_anyonecanpay (__main__.TestScriptTransactions) ... ok
test_hashsingle (__main__.TestScriptTransactions) ... ok
test_hashsingle_anyonecanpay (__main__.TestScriptTransactions) ... ok
test_literal_ops (__main__.TestScriptTransactions) ... ok
test_logic_ops (__main__.TestScriptTransactions) ... ok
test_math_overflow_ops (__main__.TestScriptTransactions) ... ok
test_multisig (__main__.TestScriptTransactions) ... ok
test_reserved_ops (__main__.TestScriptTransactions) ... ok
test_splice_ops (__main__.TestScriptTransactions) ... ok
test_stack_ops (__main__.TestScriptTransactions) ... ok
test_ternary_math_ops (__main__.TestScriptTransactions) ... ok
test_unary_math_ops (__main__.TestScriptTransactions) ... ok

----------------------------------------------------------------------
Ran 18 tests in 0.445s

OK
```
### 补充
- pycoind库使用python2.7环境

**Comment by wolfbrother** [comment]
TemplarJQ ，你捋一下pycoind的脚本验证流程，包括函数之间怎么调用，每个函数做什么的，不需要看具体实现细节。然后对比一下Edgence的脚本验证。
+ pycoind的脚本验证应该是支持大多数交易类型，如P2PK（公钥地址交易），P2PKH（公钥哈希交易），P2SH（脚本哈希交易）和多签交易
+ 而目前的Edgence，目前只支持P2PK交易。

**Comment by TemplarJQ** [comment]
# 有待修改

## Pycoind脚本验证流程

### 1.脚本验证模块
#### 1.1 script包下文件结构
  - script.py主要负责锁定脚本和解锁脚本的验证，创建并使用逆波兰表达法的栈结构
  - bytevector.py主要提供转换int与byte-vector string的转换，以及栈计算逻辑
  - opcode.py主要提供操作符与操作码的map映射
#### 1.2 script.py功能类及函数
  - 定义解锁脚本
```python
# P2PKH
TEMPLATE_PAY_TO_PUBKEY_HASH = (lambda t: len(t) == 5, opcodes.OP_DUP,
    opcodes.OP_HASH160, _is_hash160, opcodes.OP_EQUALVERIFY,
    opcodes.OP_CHECKSIG)
# P2PK
TEMPLATE_PAY_TO_PUBKEY = (lambda t: len(t) == 2, _is_pubkey,
    opcodes.OP_CHECKSIG)
```
- 验证签名并产生输出交易
```python
def check_signature(signature, public_key, hash_type, subscript, transaction, input_index):
    # figure out the hash_type and adjust the signature
    # SIGHASH_ALL/SIGHASH_NONE/SIGHASH_SINGLE/SIGHASH_ANYONECANPAY
```
- Tokenizer类，将脚本码转化为操作符
```python
class Tokenizer(object):
    # 示例
    # >>> pk_script = 'v\xa9\x14\xd6Kqr\x9aPM#\xd9H\x88\xd3\xf7\x12\xd5WS\xd5\xd6"\x88\xac'
    # >>> print
    # pycoind.Tokenizer(pk_script)
    # OP_DUP OP_HASH160 d64b71729a504d23d94888d3f712d55753d5d622 OP_EQUALVERIFY OP_CHECKSIG
```
- Script类，负责锁定脚本及解锁脚本的验证
```python
class Script(object):
    ···
    def verify_input(self, input_index, pk_script):#单输入验证，调用process
    def verify(self):#多签验证
    ···
    @staticmethod #堆栈验证过程
    def process(signature_script, pk_script, transaction, input_index, hash_type = 0):
```
### 2.脚本验证流程

**Comment by TemplarJQ** [comment]
# 有待修改

## Script脚本验证模块设计

### 1. 需求分析

### 2.交易结构分析与适配

### 3.模块与接口设计

### 4.调用流程

**Comment by TemplarJQ** [comment]
### *当前进度*

- 加入mempool的脚本验证过程
- [x] Script以及Tokenizer验证模块
- [x] check_signature函数 
- [x] UTXO中fee以及txn验证模块
- [ ] test_script测试部分

- 更改输出结构
- [x] 交易结构更改
- [x] Wallet.publickey_to_address()以及Wallet.publichash_to_address()函数
- [x] Wallet地址
- [x] 更新UTXO过程(connect_block)部分
- [ ] spend_message加密过程也即signature_script构建流程
- [ ] 客户端创建交易时signature_script构建

---
signature_script构建算法：
```python
    def :
```

**Comment by TemplarJQ** [comment]
# 模块测试

- 测试数据
- [ ] 修改接收Tokenizer字段的问题
- [ ] 修改算法加密过程报错问题
- [ ] 修改栈验证符报错问题
- [ ] script部分字段长度读取问题

**Comment by TemplarJQ** [comment]
## 客户端与服务端收发测试
- 客户端Edgehand
- [ ] 交易字段
- [ ] 构建交易方法
- 服务端EdgenceChain
- [ ] 交易字段
- [ ] coinbase方法修改
- [ ] 交易验证方法
- [ ] Mempool、coinbase中UTXO的验证内容修改

**Comment by TemplarJQ** [comment]
## 测试文档
### 1.验证输出
- 正常运作的服务端控制台输出
```shell
[2019-04-22 08:55:20,501][EdgenceChain:257] INFO begin to work in another new thread of initiative_sync
[2019-04-22 08:55:31,849][Consensus:38] INFO [consensus] mining block found at nonce=2344159 using 11.3597 s at rate 206.0 KH/s: 000000be95c123980ebc4b5e0a2501bd787a17cbb529ab646038e22831033486
[2019-04-22 08:55:31,850][BlockChain:140] INFO [ds] ##### connecting block at height #6 chain with index #0: 000000be95c123980ebc4b5e0a2501bd787a17cbb529ab646038e22831033486 
[2019-04-22 08:55:31,851][Consensus:25] INFO [consensus] mining after block 000000be95c123980ebc4b5e0a2501bd787a17cbb529ab646038e22831033486
[2019-04-22 08:55:47,420][TCPserver:400] INFO handle Balance4Addr request from Peer(ip='127.0.0.1', port=63513)
[2019-04-22 08:55:47,466][TCPserver:389] INFO handle UTXO4Addr request from Peer(ip='127.0.0.1', port=63515)
[2019-04-22 08:55:47,483][TCPserver:389] INFO handle UTXO4Addr request from Peer(ip='127.0.0.1', port=63517)
[2019-04-22 08:55:47,552][TCPserver:412] INFO [p2p] >>>>  received txn ca7473b8290f548a22149e474220aacec47cf1480d5fba78fcb1b66be2725820 from peer Peer(ip='127.0.0.1', port=63519)
[2019-04-22 08:55:47,773][UTXO_Set:113] INFO [script] Script check succeed!
[2019-04-22 08:55:47,773][MemPool:116] INFO [ds] txn ca7473b8290f548a22149e474220aacec47cf1480d5fba78fcb1b66be2725820 added to mempool
[2019-04-22 08:56:12,637][Consensus:38] INFO [consensus] mining block found at nonce=8659788 using 40.7864 s at rate 212.0 KH/s: 00000094e974e4f71f46e14aed689522c40781f837ba4efc9c791f17122a5ee1
[2019-04-22 08:56:12,638][BlockChain:140] INFO [ds] ##### connecting block at height #7 chain with index #0: 00000094e974e4f71f46e14aed689522c40781f837ba4efc9c791f17122a5ee1 
[2019-04-22 08:56:12,639][EdgenceChain:114] INFO 1 transactions selected from mempool to construct this block
[2019-04-22 08:56:12,639][Block:184] INFO [ds] fees for 1 non-coinbase transactions in this block: 0
[2019-04-22 08:56:12,640][Consensus:25] INFO [consensus] mining after block 00000094e974e4f71f46e14aed689522c40781f837ba4efc9c791f17122a5ee1
```
- 输出utxo信息
```shell
[2019-04-22 09:30:20,595][TCPserver:400] INFO handle Balance4Addr request from Peer(ip='127.0.0.1', port=64276)
[2019-04-22 09:30:20,595][TCPserver:405] INFO return Balance4Addr request and get value dict_values([UnspentTxOut(value=5000000000, to_address=b'v\xa9(fe0d26ba472c5fe910ecff4f6b4fe24b67f7575f\x88\xac', txid='8a481c86e75b0e6a8f0cb391465cf8d7aaec2b9154bc92cf1e0176f3e0c673c7', txout_idx=0, is_coinbase=True, height=2), UnspentTxOut(value=5000000000, to_address=b'v\xa9(fe0d26ba472c5fe910ecff4f6b4fe24b67f7575f\x88\xac', txid='656396bbfd268e8ace6c0b33e22f65dea2c6c8924b5ce80e44d95c636899e4ba', txout_idx=0, is_coinbase=True, height=3), UnspentTxOut(value=5000000000, to_address=b'v\xa9(fe0d26ba472c5fe910ecff4f6b4fe24b67f7575f\x88\xac', txid='59fadce0cc824f98a288876128503b8fcee8edc26d1b3d3e92406875a68401b9', txout_idx=0, is_coinbase=True, height=4), UnspentTxOut(value=5000000000, to_address=b'v\xa9(fe0d26ba472c5fe910ecff4f6b4fe24b67f7575f\x88\xac', txid='7ffdafc14f466e8c7954a9ad8145045df78f996e2954a128dc7d9f7087da2726', txout_idx=0, is_coinbase=True, height=5)])
[2019-04-22 09:30:20,630][TCPserver:389] INFO handle UTXO4Addr request from Peer(ip='127.0.0.1', port=64278)
[2019-04-22 09:30:20,676][TCPserver:389] INFO handle UTXO4Addr request from Peer(ip='127.0.0.1', port=64280)
[2019-04-22 09:30:20,738][TCPserver:412] INFO [p2p] >>>>  received txn 36994f86eedc00df9dcd6741c664a0ef43f233c0376494695ae93915c5d07c72 from peer Peer(ip='127.0.0.1', port=64282)
[2019-04-22 09:30:20,949][UTXO_Set:113] INFO [script] Script check succeed!
[2019-04-22 09:30:20,949][MemPool:116] INFO [ds] txn 36994f86eedc00df9dcd6741c664a0ef43f233c0376494695ae93915c5d07c72 added to mempool
```
utxo中to_address信息储存着上一个输出的pk_script锁定脚本

- 交易输入及验证
```shell
[2019-04-22 09:35:46,515][TCPserver:412] INFO [p2p] >>>>  received txn 807e5f94d9fbdca50ff7fe7f28891b574c489da97faad1d5220da264234ae039 from peer Peer(ip='127.0.0.1', port=64395)
[2019-04-22 09:35:46,515][TCPserver:413] INFO [p2p] >>>> txn message: Transaction(txins=[TxIn(to_spend=OutPoint(txid='8a481c86e75b0e6a8f0cb391465cf8d7aaec2b9154bc92cf1e0176f3e0c673c7', txout_idx=0), signature_script=b'@\xf1\x15\xb8\xd3L\x01\x8c\x03>*\xa9\xb0\xc5~\xcbL\x03\x98\xf4\x93\x03\x83{\x0f\x9fC\xa4\xe5\xb0\x7f\xd0\xcc`\xed<K\xf55\x9a\xe8:\xac\x1ejQm\xa5\xba\xbb\xfeD\xf6\xf7\x8d\xed\xc6+\xddQ\x9b\xec\x9b\xb5\x86@\x814L\xcf\x10UM\n\xd7\x0e_I?\xd9\xd8^3\x82cn\xea*j\x9a\xd4\x83x\xdf\xe9\xb7\xfd\x96\x1b\xc8\xe0\xf3\xa8\x1a\xc7\x1e\xf0\xea\x04\xee#\xe6\x98\xf4I\xee\xd3\xa1@\\5\xa5^@BV\x94H\x18\xf3', sequence=0)], txouts=[TxOut(value=110, pk_script=b'v\xa9(ec394803acaf0ad750aa37b8ce147ff018d83a0d\x88\xac'), TxOut(value=4999999890, pk_script=b'v\xa9(ec394803acaf0ad750aa37b8ce147ff018d83a0d\x88\xac')], locktime=None)
[2019-04-22 09:35:46,708][UTXO_Set:113] INFO [script] Script check succeed!
[2019-04-22 09:35:46,709][MemPool:116] INFO [ds] txn 807e5f94d9fbdca50ff7fe7f28891b574c489da97faad1d5220da264234ae039 added to mempool
```
接收的交易信息打印，其中解锁脚本（signature_script）部分与utxo的锁定脚本（pk_script）部分按照文档设计部分进行验证，其调用过程：
mempool.add_txn_to_mempool() >> utxo_set.validate_txn() >> valid = script.Script().verify() 

### 2.运行流程
- 交易结构
   - 交易结构为单输入多输出的形式
   - 签名方式使用"SIGN_ALL"
   - 锁定脚本为"pk_script"
   - 解锁脚本为"signature_script"
- 为测试客户端与服务端之间的通信，需要能够查询对应地址下的余额，并发送交易
   - 1）服务端先进行挖矿 >>> 产生UTXO（钱包余额）；
   - 2）拷贝服务端产生的钱包文件（mywallet.dat）并存入客户端 >>> 使客户端拥有与服务端相同的地址，“偷取”服务端的钱包余额；
   - 3）客户端交互并产生交易（花费utxo，可产生多个输出）>>> 并发送至服务端进行验证；
   - 4）服务端进行脚本验证并存入mempool中 >>> 挖矿过程将交易加入区块；

### 3.模块测试方法
#### 3.1 服务端测试
- 测试公钥与地址转化过程
```python
 # --------- Token: test_encode_decode_addr ----------
 test_encode_decode_addr()
```
- 测试Tokenizer类解析锁定与解锁脚本
```python
# --------- Token: test_token_Tokenizer ---------
# 公钥哈希
public_hash = b'fe50b84730fc9d691998c38cbcc0702d19e53610'
# 锁定脚本
test_token_tokenizer(public_hash)
# 解锁脚本
test_token_sig_tokenizer()
# 锁定脚本得到地址（用于utxo验证）
pk_script = b'v\xa9(fe0d26ba472c5fe910ecff4f6b4fe24b67f7575f\x88\xac'
print(scriptBuild.get_address_from_pk_script(pk_script))
```
- 测试编码过程
```python
 # --------- Encode: test_encode_method ----------
 pk_script = b'v\xa9(fe50b84730fc9d691998c38cbcc0702d19e53610\x88\xac'
 test_encode_method1(pk_script)
 test_encode_method2(pk_script)
```
#### 3.2 客户端测试
- 测试签名过程
```python
check_signature()
```
