### ISSUE TITLE
txid, idx = txin.to_spend 出现TypeError: 'NoneType' object is not iterable的错误

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#65]
该问题出现在主链重构的时候。

> ch: 1
[2019-03-17 20:02:16,725][TCPserver:293] INFO [p2p] side branch removed from active chain : 15e0b10b09 ,
[2019-03-17 20:02:16,726][TCPserver:344] INFO [p2p] number of blocks after slim side branch: 1
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Edgence/EdgenceChain.py", line 141, in mine_forever
    block = self.assemble_and_solve_block()
  File "/home/Edgence/EdgenceChain.py", line 94, in assemble_and_solve_block
    block = self.mempool.select_from_mempool(block, self.utxo_set)
  File "/home/Edgence/ds/MemPool.py", line 88, in select_from_mempool
    newblock = try_add_to_block(block, txid)
  File "/home/Edgence/ds/MemPool.py", line 67, in try_add_to_block
    in_mempool = self.find_utxo_in_mempool(txin)
  File "/home/Edgence/ds/MemPool.py", line 35, in find_utxo_in_mempool
    txid, idx = txin.to_spend
TypeError: 'NoneType' object is not iterable

位置是MemPool类的find_utxo_in_mempool方法里，过程是选择、添加交易到区块：
```python
    def find_utxo_in_mempool(self, txin: TxIn) -> UnspentTxOut:
        txid, idx = txin.to_spend

        try:
            txout = self.mempool[txid].txouts[idx]
        except Exception:
            logger.exception(f"[ds] could not find utxo in mempool for txin {txin}")
            return None

        return UnspentTxOut(
            *txout, txid=txid, is_coinbase=False, height=-1, txout_idx=idx)
```

**Comment by wolfbrother** [comment]
代码搞丢了，无法复现bug。
直接看主分支代码，看不明白问题所在。
