### ISSUE TITLE
timestamp too old

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#69]
bug如下：
> [2019-03-27 08:06:26,081][TCPserver:182] INFO [p2p] 4 of 50 blocks from Peer(ip='127.0.0.1', port=9997) is new
[2019-03-27 08:06:26,084][Block:187] INFO [p2p] already in another validate_block process
[2019-03-27 08:06:26,099][TCPserver:387] ERROR [p2p] block 000000d3299ae447a27dfaff99010bfc7930d2a4200092147c662ff93d6af7b9 failed validation due to internal error in this block
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/p2p/TCPserver.py", line 381, in check_block_place
    chain_idx = block.validate_block(active_chain, utxo_set, mempool, side_branches)
  File "/home/jin/.ssh/EdgenceChain/ds/Block.py", line 239, in validate_block
    raise BlockValidationError('timestamp too old')
utils.Errors.BlockValidationError: timestamp too old
[2019-03-27 08:06:26,100][TCPserver:220] INFO [p2p] orphan or wrong block 000000d3299ae447a27dfaff99010bfc7930d2a4200092147c662ff93d6af7b9
[2019-03-27 08:06:26,100][TCPserver:227] INFO [p2p] current chain height 65, and continue initial block download ... 

位于Block类的validate_block方法里：
```python
            if self.timestamp <= _get_median_time_past(11):
                raise BlockValidationError('timestamp too old')
```
而_get_median_time_past获得的是主链最新11个区块时间的中位数：
```python
        def _get_median_time_past(num_last_blocks: int) -> int:
            last_n_blocks = active_chain.chain[::-1][:num_last_blocks]
            if not last_n_blocks:
                return 0
            return last_n_blocks[len(last_n_blocks) // 2].timestamp
```

**Comment by wolfbrother** [comment]
上述问题出现在建立分支链的时候。

分支链的第一个区块产生时间比较早，而_get_median_time_past(11)计算的是主链的最近11个区块的中值。
因此，前者有很大可能会早于后者，进而产生上述问题。

**Comment by wolfbrother** [comment]
## 解决方案
```python
            prev_block, prev_block_height, prev_block_chain_idx = Block.locate_block(
                self.prev_block_hash, active_chain, side_branches)

            if not prev_block:
                raise BlockValidationError(f'prev block {self.prev_block_hash} not found in any chain',
                    to_orphan=self)

            if self.timestamp <= _get_median_time_past(prev_block, prev_block_height, prev_block_chain_idx):
                raise BlockValidationError('timestamp too old')

```

```python
        def _get_median_time_past(prev_block, prev_block_height, prev_block_chain_idx, num_last_blocks: int = 11) -> int:

            if Params.ACTIVE_CHAIN_IDX == prev_block_chain_idx:
                last_n_blocks = active_chain.chain[:prev_block_height][::-1][:num_last_blocks]
                if not last_n_blocks:
                    return 0
                return last_n_blocks[len(last_n_blocks) // 2].timestamp
            else:
                return 0
```
