### ISSUE TITLE
socket.timeout: timed out 与 BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#71]
```
[2019-03-27 13:39:43,436][TCPserver:362] INFO [EdgeHand] succeed to send TopBlocksSyncReq to Peer(ip='127.0.0.1', port=9997)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 39978)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/home/EdgenceChain-master/p2p/TCPserver.py", line 126, in handle
    self.handleBlockRev(message.data, peer)
  File "/home/EdgenceChain-master/p2p/TCPserver.py", line 363, in handleBlockRev
    msg_len = int(binascii.hexlify(s.recv(4) or b'\x00'), 16)
socket.timeout: timed out
----------------------------------------
[2019-03-27 13:39:53,448][TCPserver:176] INFO [p2p] receive TopBlockSyncReq with length 50 from peer Peer(ip='127.0.0.1', port=9997)
[2019-03-27 13:39:53,449][TCPserver:179] INFO [p2p] sending 50 blocks to Peer(ip='127.0.0.1', port=9997)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 39980)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/home/EdgenceChain-master/p2p/TCPserver.py", line 130, in handle
    self.handleTopBlockSyncReq(message.data, peer)
  File "/home/EdgenceChain-master/p2p/TCPserver.py", line 184, in handleTopBlockSyncReq
    if self.request.sendall(Utils.encode_socket_data(message)) is None:
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by wolfbrother** [comment]
## socket.timeout: timed out 
socket创建时，设置了最大维持时间 
> socket.create_connection(peer(), timeout=25)
这个例子的最大维持时间是timout为25秒。
超过这个时间，socket将在发起的一端结束。

## BrokenPipeError: [Errno 32] Broken pipe
当socket在发起端结束时，对方并不知道，因此仍然发回数据到发起的一端。
然而，socket连接已不存在，骨发生次错误。

**Comment by wolfbrother** [comment]
timeout设置为20-25s，仍然会有上述问题，说明会话时间太长了，一个请求获得回复的时间太长了。
推测如下两个原因：
+ 创建socket的with ... as ...句式，囊括的代码太多。可以将不必要的代码移到外面
+ 加锁导致，解析请求或者处理回复的代码是加了锁的，不得不排队等候。

接下来针对上述问题进行优化。

**Comment by wolfbrother** [comment]
## Utils.send_to_peer建立socket连接，但不需要回复。即对方收到数据之后，可以直接关掉socket

**Comment by wolfbrother** [comment]
## 
>[2019-03-29 07:47:44,559][EdgenceChain:210] INFO [EdgenceChain] succeed to send TopBlockReq to Peer(ip='47.102.41.81', port=9996)
[2019-03-29 07:47:45,560][EdgenceChain:220] INFO [EdgenceChain] received top block from peer Peer(ip='47.102.41.81', port=9996)
[2019-03-29 07:47:45,560][Utils:108] INFO [utils] begin to create socket connection with peer Peer(ip='127.0.0.1', port=9996)
[2019-03-29 07:47:45,561][Utils:119] INFO [utils] succeed in sending to Peer(ip='127.0.0.1', port=9996) data about 6 in 1th time
[2019-03-29 07:47:45,561][EdgenceChain:223] INFO [EdgenceChain] send BlockRev to itself

**Comment by wolfbrother** [comment]
### 方便测试的操作集合
> cd .. && rm -rf EdgenceChain && git clone git@github.com:EdgeIntelligenceChain/EdgenceChain.git && cd EdgenceChain  && cp ../Params.py params/Params.py && python3 main.py
