### ISSUE TITLE
timout与socket.create_connection失败

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#72]
### 源自EdgenceChain.initial_block_download方法
>[2019-03-29 10:45:26,391][TCPserver:62] INFO [p2p] listening on 9999
[2019-03-29 10:45:26,392][EdgenceChain:128] INFO start initial block download from 1 peers
[2019-03-29 10:45:47,416][EdgenceChain:153] INFO remove dead peer Peer(ip='2.2.2.2', port=9996)
[2019-03-29 10:45:47,418][Peer:88] INFO [p2p] saving 0 hostnames

代码如下
```python
                try:
                    with socket.create_connection(peer(), timeout=25) as s:
                        s.sendall(Utils.encode_socket_data(message))
                        logger.info(f'[EdgenceChain] succeed to send BlocksSyncReq to {peer}')
                        msg_len = int(binascii.hexlify(s.recv(4) or b'\x00'), 16)
                        data = b''
                        while msg_len > 0:
                            tdat = s.recv(1024)
                            data += tdat
                            msg_len -= len(tdat)

                    message = Utils.deserialize(data.decode(), self.gs) if data else None
                    if message:
                        logger.info(f'[EdgenceChain] received blocks from peer {peer}')
                        message = Message(Actions.BlocksSyncGet, message.data, Params.PORT_CURRENT)
                        Utils.send_to_peer(message, Peer('127.0.0.1', Params.PORT_CURRENT), itself = True)
                        #logger.info(f'[EdgenceChain] send BlocksSyncGet to itself')
                    else:
                        logger.info(f'[EdgenceChain] recv nothing from peer {peer}')
                except Exception:
                    logger.info(f'remove dead peer {peer}')
                    self.peers.remove(peer)
                    Peer.save_peers(self.peers)
```

加了打印异常信息：
```python
                except Exception as e:
                    print(repr(e))
```
则多打印一行
>timeout('timeout', )

### 源自Utils.send_to_peer方法
>[2019-03-29 10:55:57,475][Utils:113] ERROR [utils] failed to send to Peer(ip='47.111.168.213', port=9996) data about 6  in 1th time
Traceback (most recent call last):
  File "/home/EdgenceChain/utils/Utils.py", line 110, in send_to_peer
    with socket.create_connection(peer(), timeout=30) as s:
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
[2019-03-29 10:55:59,478][Peer:88] INFO [p2p] saving 1 hostnames

源码如下：
```python
            try:
                if not itself:
                    logger.info(f'[utils] begin to create socket connection with peer {peer}' )
                with socket.create_connection(peer(), timeout=30) as s:
                    s.sendall(cls.encode_socket_data(data))
            except Exception:
                logger.exception(f'[utils] failed to send to {peer} data about {data.action if hasattr(data, "action") else None} '
                                 f' in {Params.TRIES_MAXIMUM+1-tries_left}th time')
                tries_left -= 1
                time.sleep(2)
                if tries_left <= 0:
                    return False
            else:
                if not itself:
                    logger.info(f'[utils] succeed in sending to {peer} data about {data.action if hasattr(data, "action") else None}'
                            f' in {Params.TRIES_MAXIMUM+1-tries_left}th time')
```

可见，上述两个问题，都是socket的timeout引起的。

**Comment by wolfbrother** [comment]
##无连接和有连接的socket会话
### 无连接的socket会话
```python
jin@jin-VirtualBox:~/.ssh/EdgenceChain$ find . -name "*.py" |xargs grep -in "Utils.send_to_peer"
./EdgenceChain.py:149:                        Utils.send_to_peer(message, Peer('127.0.0.1', Params.PORT_CURRENT), itself = True)
./EdgenceChain.py:178:                        if Utils.send_to_peer(Message(Actions.BlockRev, block, Params.PORT_CURRENT), _peer) is False:
./EdgenceChain.py:223:                        Utils.send_to_peer(message, Peer('127.0.0.1', Params.PORT_CURRENT), itself = True)
./p2p/TCPserver.py:158:                Utils.send_to_peer(Message(Actions.PeerExtend, peer_samples, Params.PORT_CURRENT), _peer)
./p2p/TCPserver.py:321:            Utils.send_to_peer(message, Peer('127.0.0.1', Params.PORT_CURRENT), itself = True)
./p2p/TCPserver.py:378:                                Utils.send_to_peer(Message(Actions.TxRev, txn, Params.PORT_CURRENT), _peer)
./p2p/TCPserver.py:402:                            Utils.send_to_peer(Message(Actions.BlockRev, block, Params.PORT_CURRENT), _peer)
./p2p/TCPserver.py:424:                    Utils.send_to_peer(message, Peer('127.0.0.1', Params.PORT_CURRENT), itself = True)

```

**Comment by wolfbrother** [comment]
目前上述socket建立连接的方式，都改成了如下语句：
```python
                    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s: #socket.create_connection(peer(), timeout=25) as s:
                        s.connect(peer())
```

**Comment by wolfbrother** [comment]
>[2019-03-30 13:36:27,164][Utils:113] INFO [utils] begin to create socket connection with peer Peer(ip='161.117.84.146', port=9996)
[2019-03-30 13:36:27,164][Consensus:30] INFO [consensus] mining interrupted +++ 2578
[2019-03-30 13:36:27,268][Utils:120] ERROR [utils] ConnectionRefusedError(111, 'Connection refused'), failed to send to Peer(ip='161.117.84.146', port=9996) data about PeerExtend  in 1th time
Traceback (most recent call last):
  File "/home/EdgenceChain/utils/Utils.py", line 115, in send_to_peer
    s.connect(peer())######
ConnectionRefusedError: [Errno 111] Connection refused
[2019-03-30 13:36:29,271][Peer:106] INFO [p2p] saving 2 hostnames

**Comment by wolfbrother** [comment]
## 局域网节点连接公网节点，timeout问题尤甚
分别ping公网四个节点，能正常通，时间分别是917、80、200、120ms。

**Comment by wolfbrother** [comment]
局域网节点连接阿里云北京数据中心的服务器，能连接上。

**Comment by wolfbrother** [comment]
TimeoutError: [Errno 110] Connection timed out

时延导致的。
