### ISSUE TITLE
局域网节点的节点管理

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#73]
局域网节点在与公网节点的一次会话中，后者不能担任会话发起节点。不然，会因为无法找到前者，而不能成功地建立通信连接。

而公网节点在会话里，会添加局域网节点的地址信息到自己的节点列表。然而，这个地址却是无效的。公网节点主动建立会话，并向这个地址发送消息，则不能成功建立连接，然后将其从节点列表剔除。下次由局域网节点发起的会话里，会再次添加该节点。

循环不止，浪费资源。

这是接入局域网节点所必备的功能。

**Comment by wolfbrother** [comment]
连接遭拒，并未删除节点

>[2019-03-29 20:47:14,666][Utils:113] INFO [utils] begin to create socket connection with peer Peer(ip='47.88.63.126', port=9996)
[2019-03-29 20:47:14,865][Utils:119] ERROR [utils] Error: ConnectionRefusedError(111, 'Connection refused'), and failed to send to Peer(ip='47.88.63.126', port=9996) data about PeerExtend  in 1th time
Traceback (most recent call last):
  File "/home/EdgenceChain/utils/Utils.py", line 114, in send_to_peer
    with socket.create_connection(peer(), timeout=30) as s:
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by wolfbrother** [comment]
```python
    def send_to_peer(cls, data, peer, itself: bool = False)->bool:

        from p2p.Message import Actions
        from p2p.Message import Message

        tries_left = int(Params.TRIES_MAXIMUM)

        if tries_left <= 0:
            logger.info(f'[utils] initial tries_left is less than 1, will not send data to other nodes')
            return -2

        while tries_left > 0:

            try:
                if not itself:
                    logger.info(f'[utils] begin to create socket connection with peer {peer}' )
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s: #socket.create_connection(peer(), timeout=30) as s:
                    s.connect(peer())######
                    #logger.info(f'[Utils] succeed to create socket connection with {peer}')
                    s.sendall(cls.encode_socket_data(data))
                    #logger.info(f'[Utils] succeed to send data to {peer}')
            except ConnectionRefusedError as e:
                logger.exception(f'[utils] {repr(e)}, failed to send to {peer} data about {Actions.num2name[str(data.action)] if hasattr(data, "action") else None} '
                                 f' in {Params.TRIES_MAXIMUM+1-tries_left}th time')
                try:
                    s.close()
                except:
                    pass
                tries_left -= 1
                time.sleep(2)
                if tries_left <= 0:
                    return 1
            except TimeoutError as e:
                logger.exception(f'[utils] {repr(e)}, failed to send to {peer} data about {Actions.num2name[str(data.action)] if hasattr(data, "action") else None} '
                                 f' in {Params.TRIES_MAXIMUM+1-tries_left}th time')
                try:
                    s.close()
                except:
                    pass
                tries_left -= 1
                time.sleep(2)
                if tries_left <= 0:
                    return 2
            except BrokenPipeError as e:
                logger.exception(f'[utils] {repr(e)}, failed to send to {peer} data about {Actions.num2name[str(data.action)] if hasattr(data, "action") else None} '
                                 f' in {Params.TRIES_MAXIMUM+1-tries_left}th time')
                try:
                    s.close()
                except:
                    pass
                tries_left -= 1
                time.sleep(2)
                if tries_left <= 0:
                    return 3
            except Exception as e:
                logger.exception(f'[utils] {repr(e)}, failed to send to {peer} data about {Actions.num2name[str(data.action)] if hasattr(data, "action") else None} '
                                 f' in {Params.TRIES_MAXIMUM+1-tries_left}th time')
                try:
                    s.close()
                except:
                    pass
                tries_left -= 1
                time.sleep(2)
                if tries_left <= 0:
                    return -1
            else:
                try:
                    s.close()
                except:
                    pass
                if not itself:
                    logger.info(f'[utils] succeed in sending to {peer} data about {Actions.num2name[str(data.action)] if hasattr(data, "action") else None}'
                            f' in {Params.TRIES_MAXIMUM+1-tries_left}th time')
                return 0

```

**Comment by wolfbrother** [comment]
每收到一个新节点，需要尝试与其建立socket链接，以此来检查该节点是否有效，然后决定是否将其加入到节点列表。
>[2019-03-30 13:36:27,164][Utils:113] INFO [utils] begin to create socket connection with peer Peer(ip='161.117.84.146', port=9996)
[2019-03-30 13:36:27,164][Consensus:30] INFO [consensus] mining interrupted +++ 2578
[2019-03-30 13:36:27,268][Utils:120] ERROR [utils] ConnectionRefusedError(111, 'Connection refused'), failed to send to Peer(ip='161.117.84.146', port=9996) data about PeerExtend  in 1th time
Traceback (most recent call last):
  File "/home/EdgenceChain/utils/Utils.py", line 115, in send_to_peer
    s.connect(peer())######
ConnectionRefusedError: [Errno 111] Connection refused
[2019-03-30 13:36:29,271][Peer:106] INFO [p2p] saving 2 hostnames

添加节点到节点列表有如下几处：
>jin@jin-VirtualBox:~/.ssh/EdgenceChain$ find . -name "*.py" |xargs grep -in "peers.append"
./p2p/Peer.py:65:                    peers.append(peer)
./p2p/TCPserver.py:192:            self.peers.append(peer)
./p2p/TCPserver.py:214:                self.peers.append(peer)
./p2p/TCPserver.py:235:                self.peers.append(peer)
./p2p/TCPserver.py:302:            self.peers.append(peer)
./p2p/TCPserver.py:574:            self.peers.append(peer_sample)
