### ISSUE TITLE
AttributeError: 'int' object has no attribute 'id什么鬼

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#77]
handleBlockSyncGet的错误，收到的数据应该是Iterable[Block]，然而收到的是Block
```
[2019-03-30 04:02:15,716][EdgenceChain:140] INFO [EdgenceChain] succeed to send BlocksSyncReq to Peer(ip='47.88.63.126', port=9996)
[2019-03-30 04:02:15,737][EdgenceChain:151] INFO [EdgenceChain] received blocks in initial_block_download from peer Peer(ip='47.88.63.126', port=9996)
[2019-03-30 04:02:15,738][EdgenceChain:136] INFO [EdgenceChain] begin to connect to Peer(ip='47.111.168.213', port=9996)
[2019-03-30 04:02:15,740][TCPserver:250] INFO [p2p] receive 7 blocks for BlockSyncGet from Peer(ip='47.88.63.126', port=9996)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55766)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/home/EdgenceChain/p2p/TCPserver.py", line 122, in handle
    self.handleBlockSyncGet(message.data, peer)
  File "/home/EdgenceChain/p2p/TCPserver.py", line 251, in handleBlockSyncGet
    new_blocks = [block for block in blocks if not Block.locate_block(block.id, self.active_chain, self.side_branches)[0]]
  File "/home/EdgenceChain/p2p/TCPserver.py", line 251, in <listcomp>
    new_blocks = [block for block in blocks if not Block.locate_block(block.id, self.active_chain, self.side_branches)[0]]
AttributeError: 'int' object has no attribute 'id
```

**Comment by wolfbrother** [comment]
分别打印出的blocks和block列表信息。可以看到这里的blocks其实就是个block：
```
exception: blocks:  Block(version=0, prev_block_hash='000000f89367ec61c17a0574ca009d781d963f9f42d0ede6c9e6bdfab9839682', merkle_hash='f06ce71675d77fb2546a9877d278a183d909a4987bc2d898a1df4e2a54f2ac28', timestamp=1553937481, bits=22, nonce=2509725, txns=[Transaction(txins=[TxIn(to_spend=None, unlock_sig=b'435', unlock_pk=None, sequence=0)], txouts=[TxOut(value=5000000000, to_address="b'1HitpAdEwFqe3pqvbaSizMqLXY3iJrJENs'")], locktime=None)])
for block:  [0, '000000f89367ec61c17a0574ca009d781d963f9f42d0ede6c9e6bdfab9839682', 'f06ce71675d77fb2546a9877d278a183d909a4987bc2d898a1df4e2a54f2ac28', 1553937481, 22, 2509725, [Transaction(txins=[TxIn(to_spend=None, unlock_sig=b'435', unlock_pk=None, sequence=0)], txouts=[TxOut(value=5000000000, to_address="b'1HitpAdEwFqe3pqvbaSizMqLXY3iJrJENs'")], locktime=None)]]
^CTraceback (most recent call last):
  File "main.py", line 7, in <module>
    edgencechain.start()
  File "/home/EdgenceChain/EdgenceChain.py", line 263, in start
    self.initial_block_download()
  File "/home/EdgenceChain/EdgenceChain.py", line 137, in initial_block_download
    s.connect(peer())
KeyboardInterrupt
```

**Comment by wolfbrother** [comment]
handleBlockSyncReq找不到要求的id的区块时，会回复最高区块，以BlockRev的形式
```python
    def handleBlockSyncReq(self, blockid: str, peer: Peer):

        logger.info(f"[p2p] receive BlockSyncReq from peer {peer}")


        #with self.chain_lock:
        height = Block.locate_block(blockid, self.active_chain)[1]
        if height is None:
            logger.info(f'[p2p] cannot find blockid {blockid}, and do nothing for this BlockSyncReq from peer {peer}')
            message = Message(Actions.BlockRev, self.active_chain.chain[-1], Params.PORT_CURRENT)
            self.request.sendall(Utils.encode_socket_data(message))

            return
```
