### ISSUE TITLE
运行出错是怎么回事？

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#8]
https://github.com/EdgeIntelligenceChain/EdgenceChain/blob/a68e452072e6a0473d1d299d86347389d13d13fa/edgencechain/__main__.py#L44

`
jin@jin-VirtualBox:~/cbozi-EdgenceChain$ python3 edgencechain
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "edgencechain/__main__.py", line 8, in <module>
    from edgencechain.chain import (GetBlocksMsg, TCPHandler, ThreadedTCPServer,
  File "edgencechain/../edgencechain/__init__.py", line 1, in <module>
    from edgencechain.chain import *
  File "edgencechain/../edgencechain/chain.py", line 15, in <module>
    from edgencechain.definitions import (Block, BlockValidationError, OutPoint,
  File "edgencechain/../edgencechain/definitions.py", line 4, in <module>
    from edgencechain.helpers import serialize, sha256d
  File "edgencechain/../edgencechain/helpers.py", line 11, in <module>
    import edgencechain.definitions as defs
AttributeError: module 'edgencechain' has no attribute 'definitions'

`

**Comment by cbozi** [comment]
路径重复了，不要放在“edgencechain”父文件夹下

**Comment by wolfbrother** [comment]
上述问题的产生，是python版本不同导致的包引用方式的差异。针对3.6.7版本的修正分支是： ly_fix_bug_of_cbozi
