### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#81]
```
[2019-04-01 07:38:57,575][BlockChain:143] INFO [ds] ##### connecting block at height #727 chain with index: 0: 00000104c004036ce0531d1e572784a948db15ede14f6823661b1cd8d565fcf9 
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45718)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/EdgenceChain/p2p/TCPserver.py", line 125, in handle
    self.handleBlockSyncGet(message.data, peer)
  File "/EdgenceChain/p2p/TCPserver.py", line 306, in handleBlockSyncGet
    self.mempool, self.utxo_set, self.mine_interrupt, self.peers):
  File "/EdgenceChain/p2p/TCPserver.py", line 525, in do_connect_block_and_after
    mempool, utxo_set, mine_interrupt, peers)
  File "/EdgenceChain/ds/BlockChain.py", line 163, in connect_block
    reorg_and_succeed = _reorg_and_succeed(active_chain, side_branches, mempool, utxo_set, mine_interrupt, peers)
  File "/EdgenceChain/ds/BlockChain.py", line 131, in _reorg_and_succeed
    branch_height_real = branch_chain.height + fork_height
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```
上述问题发生在每次添加区块到主分支之后，查看是否应该主链重构的过程发生的。原因在于通过
>fork_block, fork_height, _ = Block.locate_block(branch_chain.chain[0].prev_block_hash, active_chain)

获得的fork_height为None，即分支链首个区块的前向哈希指代的区块，并不能在主分支找到。然后在做加法运算的时候，出错。

**Comment by wolfbrother** [comment]
### 查找原因

+ connect_block._reorg_and_succeed._do_reorg这个函数，只负责重构指定的分支链branch_idx，而对于重构之后的其它的分支链，并没有做相应的处理。
+ 上一步有可能的发生的情况是，重构之后， 另一个分支链的首个区块的前向区块，从主分支上删掉了。
+ 那么，就会出现最初的错误。

**Comment by wolfbrother** [comment]
### 问题之外
+ 如果connect_block的链主体是主分支，则肯定不重构；
+ connect_block的链主体是某个分支链，则只需要检查该分支链即可，不用依次检查每个分支链。

根据这两个规律，可以对代码进行优化。
