### ISSUE TITLE
分支的分支，非处理不可

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#85]
某节点遇到如下问题，即不断地收到某个节点Peer(ip='172.106.33.51', port=9996)的恶意请求：
```
[2019-04-01 11:06:59,641][TCPserver:215] INFO [p2p] to handle TopBlockSyncReq with length 50 from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:06:59,656][TCPserver:220] INFO [p2p] sent 50 blocks in handleTopBlockSyncReq to Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:06:59,916][TCPserver:180] INFO [p2p] receive BlockSyncReq from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:06:59,924][TCPserver:186] INFO [p2p] cannot find blockid 000005fd85cc097ef0664b7fb2aa1481fa5b08130543fac87b16c8336bf69587, and do nothing for this BlockSyncReq from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:06:59,937][TCPserver:215] INFO [p2p] to handle TopBlockSyncReq with length 50 from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:06:59,957][TCPserver:220] INFO [p2p] sent 50 blocks in handleTopBlockSyncReq to Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,203][TCPserver:180] INFO [p2p] receive BlockSyncReq from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,212][TCPserver:186] INFO [p2p] cannot find blockid 000005fd85cc097ef0664b7fb2aa1481fa5b08130543fac87b16c8336bf69587, and do nothing for this BlockSyncReq from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,224][TCPserver:215] INFO [p2p] to handle TopBlockSyncReq with length 50 from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,240][TCPserver:220] INFO [p2p] sent 50 blocks in handleTopBlockSyncReq to Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,490][TCPserver:180] INFO [p2p] receive BlockSyncReq from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,504][TCPserver:186] INFO [p2p] cannot find blockid 000005fd85cc097ef0664b7fb2aa1481fa5b08130543fac87b16c8336bf69587, and do nothing for this BlockSyncReq from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,517][TCPserver:215] INFO [p2p] to handle TopBlockSyncReq with length 50 from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,541][TCPserver:220] INFO [p2p] sent 50 blocks in handleTopBlockSyncReq to Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,553][TCPserver:180] INFO [p2p] receive BlockSyncReq from peer Peer(ip='47.92.85.186', port=10000)
[2019-04-01 11:07:00,567][TCPserver:186] INFO [p2p] cannot find blockid 000005788021c58cb6027bd756c45a59a6a8ad32df1200c9b4b31d88026f2ed3, and do nothing for this BlockSyncReq from peer Peer(ip='47.92.85.186', port=10000)
[2019-04-01 11:07:00,809][TCPserver:180] INFO [p2p] receive BlockSyncReq from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,816][TCPserver:186] INFO [p2p] cannot find blockid 000005fd85cc097ef0664b7fb2aa1481fa5b08130543fac87b16c8336bf69587, and do nothing for this BlockSyncReq from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,828][TCPserver:215] INFO [p2p] to handle TopBlockSyncReq with length 50 from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:00,843][TCPserver:220] INFO [p2p] sent 50 blocks in handleTopBlockSyncReq to Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:01,097][TCPserver:180] INFO [p2p] receive BlockSyncReq from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-01 11:07:01,104][TCPserver:186] INFO [p2p] cannot find blockid 000005fd85cc097ef0664b7fb2aa1481fa5b08130543fac87b16c8336bf69587, and do nothing for this BlockSyncReq from peer Peer(ip='172.106.33.51', port=9996)
```

查看该恶意节点的日志，发现原来是分支的分支出现了问题：
```
[2019-04-01 15:06:56,991][TCPserver:310] INFO [p2p] orphan or wrong block 0000028c189d81abc36711e44955ffce16c875014be992f2b6d48d8a77912ab7
[2019-04-01 15:06:57,070][TCPserver:321] INFO [p2p] current chain height 748, and continue initial block download ... 
[2019-04-01 15:06:57,071][TCPserver:347] INFO [p2p] succeed to send BlocksSyncReq to Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,080][TCPserver:357] INFO [p2p] received blocks from peer Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,082][TCPserver:437] INFO [p2p] received block 0000061570275ec89d95bccb9254f90484cc3ebe2f8ac65d4ed325d988406e12 from peer Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,088][TCPserver:607] INFO [p2p]  block 0000061570275ec89d95bccb9254f90484cc3ebe2f8ac65d4ed325d988406e12 failed validation as an orphan block
[2019-04-01 15:06:57,089][TCPserver:488] INFO [p2p] succeed to send TopBlocksSyncReq to Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,111][TCPserver:498] INFO [p2p] received blocks from peer Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,124][TCPserver:273] INFO [p2p] receive 50 blocks for BlockSyncGet from Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,173][TCPserver:498] INFO [p2p] received blocks from peer Peer(ip='39.97.166.176', port=9996)
[2019-04-01 15:06:57,249][TCPserver:273] INFO [p2p] receive 50 blocks for BlockSyncGet from Peer(ip='39.97.166.176', port=9996)
[2019-04-01 15:06:57,315][TCPserver:275] INFO [p2p] 8 of 50 blocks from Peer(ip='45.58.54.216', port=9996) is new
[2019-04-01 15:06:57,329][TCPserver:610] ERROR [p2p] block 0000028c189d81abc36711e44955ffce16c875014be992f2b6d48d8a77912ab7 failed validation due to internal error in this block
Traceback (most recent call last):
  File "/home/EdgenceChain/p2p/TCPserver.py", line 604, in check_block_place
    chain_idx = block.validate_block(active_chain, utxo_set, mempool, side_branches)
  File "/home/EdgenceChain/ds/Block.py", line 252, in validate_block
    raise BlockValidationError('branch of an existing branch chain, which is not supported')
utils.Errors.BlockValidationError: branch of an existing branch chain, which is not supported
[2019-04-01 15:06:57,340][TCPserver:310] INFO [p2p] orphan or wrong block 0000028c189d81abc36711e44955ffce16c875014be992f2b6d48d8a77912ab7
[2019-04-01 15:06:57,517][TCPserver:275] INFO [p2p] 9 of 50 blocks from Peer(ip='39.97.166.176', port=9996) is new
[2019-04-01 15:06:57,517][TCPserver:321] INFO [p2p] current chain height 748, and continue initial block download ... 
[2019-04-01 15:06:57,526][TCPserver:610] ERROR [p2p] block 0000028c189d81abc36711e44955ffce16c875014be992f2b6d48d8a77912ab7 failed validation due to internal error in this block
Traceback (most recent call last):
  File "/home/EdgenceChain/p2p/TCPserver.py", line 604, in check_block_place
    chain_idx = block.validate_block(active_chain, utxo_set, mempool, side_branches)
  File "/home/EdgenceChain/ds/Block.py", line 252, in validate_block
    raise BlockValidationError('branch of an existing branch chain, which is not supported')
utils.Errors.BlockValidationError: branch of an existing branch chain, which is not supported
[2019-04-01 15:06:57,527][TCPserver:310] INFO [p2p] orphan or wrong block 0000028c189d81abc36711e44955ffce16c875014be992f2b6d48d8a77912ab7
[2019-04-01 15:06:57,538][TCPserver:347] INFO [p2p] succeed to send BlocksSyncReq to Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,554][TCPserver:357] INFO [p2p] received blocks from peer Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,576][TCPserver:437] INFO [p2p] received block 0000061570275ec89d95bccb9254f90484cc3ebe2f8ac65d4ed325d988406e12 from peer Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,594][TCPserver:607] INFO [p2p]  block 0000061570275ec89d95bccb9254f90484cc3ebe2f8ac65d4ed325d988406e12 failed validation as an orphan block
[2019-04-01 15:06:57,616][TCPserver:488] INFO [p2p] succeed to send TopBlocksSyncReq to Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,643][TCPserver:498] INFO [p2p] received blocks from peer Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,644][TCPserver:321] INFO [p2p] current chain height 748, and continue initial block download ... 
[2019-04-01 15:06:57,658][TCPserver:273] INFO [p2p] receive 50 blocks for BlockSyncGet from Peer(ip='45.58.54.216', port=9996)
[2019-04-01 15:06:57,794][TCPserver:275] INFO [p2p] 8 of 50 blocks from Peer(ip='45.58.54.216', port=9996) is new
[2019-04-01 15:06:57,802][TCPserver:610] ERROR [p2p] block 0000028c189d81abc36711e44955ffce16c875014be992f2b6d48d8a77912ab7 failed validation due to internal error in this block
Traceback (most recent call last):
  File "/home/EdgenceChain/p2p/TCPserver.py", line 604, in check_block_place
    chain_idx = block.validate_block(active_chain, utxo_set, mempool, side_branches)
  File "/home/EdgenceChain/ds/Block.py", line 252, in validate_block
    raise BlockValidationError('branch of an existing branch chain, which is not supported')
utils.Errors.BlockValidationError: branch of an existing branch chain, which is not supported
```

**Comment by wolfbrother** [comment]
Block.validate_block方法里，当检测到新区块应该是分支的分支时，也返回一个大1号的分支链序号，而非抛出异常：
```python
            if prev_block_chain_idx != Params.ACTIVE_CHAIN_IDX:
                if prev_block == side_branches[prev_block_chain_idx-1].chain[-1]:
                    return prev_block_chain_idx
                else:
                    #raise BlockValidationError('branch of an existing branch chain, which is not supported')
                    return len(side_branches)+1
```
这个序号由check_block_place获得。
