### ISSUE TITLE
PeerManager节点管理包

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#87]
对节点管理功能进行封装，以支持更多功能。

核心是每个节点附带了三种状态，并且实现了不同状态之间的转换规则。
+ blocked 。节点被blocked。
+ unblocked。未被blocked
+ black list 。 加入黑名单

**Comment by wolfbrother** [comment]
安装bitarray包，有如下错误：
```
root@iZbp1it9lc0o7e32ucimusZ:/EdgenceChain# python3.6 -m pip install bitarray
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/python36/lib/python3.6/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal import main as _main  # noqa
  File "/usr/local/python36/lib/python3.6/site-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/usr/local/python36/lib/python3.6/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/usr/local/python36/lib/python3.6/site-packages/pip/_internal/index.py", line 25, in <module>
    from pip._internal.download import HAS_TLS, is_url, path_to_url, url_to_path
  File "/usr/local/python36/lib/python3.6/site-packages/pip/_internal/download.py", line 35, in <module>
    from pip._internal.locations import write_delete_marker_file
  File "/usr/local/python36/lib/python3.6/site-packages/pip/_internal/locations.py", line 10, in <module>
    from distutils import sysconfig as distutils_sysconfig
ImportError: cannot import name 'sysconfig'
```

### 解决

**Comment by wolfbrother** [comment]
## 节点由三种状态：
+ blocked 。节点被blocked。
+ unblocked。未被blocked
+ black list 。 加入黑名单

**Comment by wolfbrother** [comment]
Utils.send_to_peer返回的是int类型，针对不同的socket错误，有不同的值。当节点不存在， 其内部捕获到refused错误，返回值1.
Utils.is_peer_valid返回值是bool类型，当内部捕获到refused错误，返回False。
