### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#91]
```
[2019-04-04 08:21:12,415][TCPserver:286] INFO [p2p] do nothing for block 0000007fb6612339a98a0d6953a99c5c1363195be18ce8d1e180d1c5fda56cbd
[2019-04-04 08:21:12,415][TCPserver:286] INFO [p2p] do nothing for block 0000021e2b1f7f8af54054ae8a7e6ce821ccfe0903b6ba3d3f43972c0de6afb8
[2019-04-04 08:21:12,416][TCPserver:286] INFO [p2p] do nothing for block 000003a7eaf6784e607cf1ab3534b644da89ab22e85467626043d27382e0a055
[2019-04-04 08:21:12,416][TCPserver:286] INFO [p2p] do nothing for block 00000073f01bcb97765b3734c098a8f62b697172acbcc86188fa9ed37aa424fe
[2019-04-04 08:21:12,416][TCPserver:286] INFO [p2p] do nothing for block 000000986f6826193d340349df579c51246a270137d64060bc68018b26a191be
[2019-04-04 08:21:12,416][TCPserver:286] INFO [p2p] do nothing for block 000000a8fb7fabb75cf0c60889129d0afc24f630baa0b0f8d851bd40c740b680
[2019-04-04 08:21:12,416][TCPserver:286] INFO [p2p] do nothing for block 0000032436f2587c50672132413e2388c6d266ed5acec96d5d1bb5c1bf064e30
[2019-04-04 08:21:12,416][TCPserver:286] INFO [p2p] do nothing for block 00000347e5bce85f3a24ba0bf57574b30fb95010887c9a437c2d11f8188eb622
[2019-04-04 08:21:10,405][TCPserver:341] INFO [p2p] received blocks from peer Peer(ip='47.111.168.213', port=9996)
[2019-04-04 08:21:10,415][TCPserver:341] INFO [p2p] received blocks from peer Peer(ip='172.106.33.51', port=9996)
[2019-04-04 08:21:08,411][TCPserver:324] INFO [p2p] succeed to send BlocksSyncReq to Peer(ip='161.117.84.146', port=9996)
[2019-04-04 08:21:12,436][PeerManager:62] INFO add log of result 0 from connecting to Peer(ip='161.117.84.146', port=9996)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 35516)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 666, in process_request
    t.start()
  File "/usr/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
----------------------------------------
[2019-04-04 08:21:10,444][TCPserver:241] INFO [p2p] receive 50 blocks for BlockSyncGet from Peer(ip='39.97.166.176', port=9996)
[2019-04-04 08:21:12,416][TCPserver:286] INFO [p2p] do nothing for block 000000144a3c2f15a606714fbcb2a3abcd0b11455386cc1a4ce569be4bffe419
```

**Comment by wolfbrother** [comment]
线程开得太多了

**Comment by wolfbrother** [comment]
```python
    def handleBlockSyncGet(self, blocks: Iterable[Block], peer: Peer):
        if peer != Peer('127.0.0.1', Params.PORT_CURRENT):
            logger.info(f"[p2p] receive {len(blocks)} blocks for BlockSyncGet from {peer}")
        new_blocks = [block for block in blocks if not Block.locate_block(block.id, self.active_chain, self.side_branches)[0]]
        logger.info(f'[p2p] {len(new_blocks)} of {len(blocks)} blocks from {peer} is new')

        if not new_blocks:
            logger.info('[p2p] initial block download complete')
            self.ibd_done.set()
            return
        else:
            self.ibd_done.clear()
        if not TCPHandler.check_blocks_headers(new_blocks):
            return


        with self.chain_lock:

            chain_idx  = TCPHandler.check_block_place(new_blocks[0], self.active_chain, self.utxo_set, \
                                                          self.mempool, self.side_branches)
            if chain_idx is None:
                logger.info(f'received blocks have been seen in BlockSyncGet, do nothing and return')
                return
            if chain_idx <= -1:
                logger.info(f'[p2p] orphan or wrong blocks')
                if peer != Peer('127.0.0.1', Params.PORT_CURRENT):
                    with self.peers_lock:
                        self.peerManager.block(peer)
                return

            if chain_idx >= 1:
                # if is side branches, append the blocks (one block left) to the side branches directly
                logger.info(f'[p2p] just append {len(new_blocks)-1} blocks to side branch {chain_idx}, leaving one block to '
                f'be coped with method do_connect_block_and_after')
                while len(new_blocks) >= 2:
                    self.side_branches[chain_idx-1].chain.append(new_blocks.pop(0))


            for block in new_blocks:
                if not TCPHandler.do_connect_block_and_after(block, chain_idx, self.active_chain, self.side_branches, \
                                                self.mempool, self.utxo_set, self.mine_interrupt):
                    return


        if chain_idx == Params.ACTIVE_CHAIN_IDX:
            if len(self.active_chain.chain) % Params.SAVE_PER_SIZE == 0 or len(self.active_chain.chain) <= 5:
                Persistence.save_to_disk(self.active_chain)

            logger.info(f'[p2p] current chain height {self.active_chain.height}, and continue initial block download ... ')

        if peer not in self.peerManager.getPeers():
            if peer== Peer('127.0.0.1', Params.PORT_CURRENT) or \
                            peer == Peer('localhost', Params.PORT_CURRENT) or \
                                peer.ip == '0.0.0.0' or \
                                peer == Peer(Params.PUBLIC_IP, Params.PORT_CURRENT):
                return
            if Utils.is_peer_valid(peer):
                with self.peers_lock:
                    self.peerManager.add(peer)#self.peers.append(peer)
                self.sendPeerExtend()
            else:
                self.peerManager.block(peer)



        if peer == Peer('127.0.0.1', Params.PORT_CURRENT):
            logger.info(f'peer in handleBlockSyncGet cannot be itself')
            return

        top_id_chain_idx = new_blocks[-1].id
        message = Message(Actions.BlocksSyncReq, top_id_chain_idx, Params.PORT_CURRENT)
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.connect(peer())
                s.sendall(Utils.encode_socket_data(message))
                logger.info(f'[p2p] succeed to send BlocksSyncReq to {peer}')
                msg_len = int(binascii.hexlify(s.recv(4) or b'\x00'), 16)
                data = b''
                while msg_len > 0:
                    tdat = s.recv(1024)
                    data += tdat
                    msg_len -= len(tdat)
            s.close()
        except ConnectionRefusedError:
            self.peerManager.block(peer)
        except:
            self.peerManager.addLog(peer, 1)
        else:
            self.peerManager.addLog(peer, 0)

            message = Utils.deserialize(data.decode(), self.gs) if data else None
            if message:
                logger.info(f'[p2p] received blocks for sync blocks from peer {peer}')
                message = Message(message.action, message.data, Params.PORT_CURRENT, peer)
                ret = Utils.send_to_peer(message, Peer('127.0.0.1', Params.PORT_CURRENT), itself = True)
                if ret != 0:
                    logger.info(f'[p2p] cannot send data to itself, and its current port is {Params.PORT_CURRENT}')

            else:
                logger.info(f'[p2p] recv nothing from peer {peer}')
```

**Comment by wolfbrother** [comment]
引起更多线程
+ 同步成功之后，会给自己发一个同步请求
```python
                 message = Message(message.action, message.data, Params.PORT_CURRENT, peer)
                ret = Utils.send_to_peer(message, Peer('127.0.0.1', Params.PORT_CURRENT), itself = True)
```
+

**Comment by wolfbrother** [comment]
推测是handleBlockRev收到孤儿块导致的。
做如下修改：当收到孤儿块时，向对方发同步区块请求，然后对方发最高的50个区块，如果发现该50个区块的第一个区块的前向区块在链上找不到，则block对方。
```python
            elif chain_idx == -1:
                #case of orphan block
                message = Message(Actions.TopBlocksSyncReq, 50, Params.PORT_CURRENT)
                if peer == Peer('127.0.0.1', Params.PORT_CURRENT):
                    peer = random.sample(self.peerManager.getPeers(),1)[0]

                try:
                    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:#socket.create_connection(peer(), timeout=25) as s:
                        s.connect(peer())
                        s.sendall(Utils.encode_socket_data(message))
                        logger.info(f'[p2p] succeed to send TopBlocksSyncReq to {peer}')
                        msg_len = int(binascii.hexlify(s.recv(4) or b'\x00'), 16)
                        data = b''
                        while msg_len > 0:
                            tdat = s.recv(1024)
                            data += tdat
                            msg_len -= len(tdat)
                    s.close()
                except ConnectionRefusedError:
                    self.peerManager.block(peer)
                except:
                    self.peerManager.addLog(peer, 1)
                else:
                    self.peerManager.addLog(peer, 0)

                    message = Utils.deserialize(data.decode(), self.gs) if data else None
                    if message:
                        new_blocks = [block for block in message.data if not Block.locate_block(block.id, self.active_chain, self.side_branches)[0]]
                        logger.info(f'[p2p] [p2p] received blocks from {peer}, and {len(new_blocks)} of {len(blocks)} blocks is new')

                        if not new_blocks:
                            self.peerManager.block(peer)

```

**Comment by wolfbrother** [comment]
```
[2019-04-05 05:59:29,831][TCPserver:507] INFO received sync blocks for the orphan block in handleBlockRev, but the first blocks's pre_block_hash cannot be seen on the chains
[2019-04-05 05:59:29,831][PeerManager:103] INFO [p2p] block Peer(ip='161.117.84.146', port=9996) in PeerManager
[2019-04-05 05:59:29,838][TCPserver:487] INFO [p2p] succeed to send TopBlocksSyncReq to Peer(ip='47.102.41.81', port=9996)
[2019-04-05 05:59:29,905][PeerManager:69] INFO [p2p] Peer(ip='161.117.84.146', port=9996) is already in PeerManager
[2019-04-05 05:59:29,906][PeerManager:69] INFO [p2p] Peer(ip='45.58.54.216', port=9996) is already in PeerManager
[2019-04-05 05:59:29,979][TCPserver:428] INFO [p2p] received block 00000378d3e8e5e92cee55cfc19c14a3e50ef65f2a94ccdde1d1117d0a8b4be1 from peer Peer(ip='39.97.166.176', port=9996)
[2019-04-05 05:59:29,980][TCPserver:640] INFO [p2p]  block 00000378d3e8e5e92cee55cfc19c14a3e50ef65f2a94ccdde1d1117d0a8b4be1 failed validation as an orphan block
[2019-04-05 05:59:30,066][PeerManager:69] INFO [p2p] Peer(ip='47.102.41.81', port=9996) is already in PeerManager
[2019-04-05 05:59:30,180][TCPserver:507] INFO received sync blocks for the orphan block in handleBlockRev, but the first blocks's pre_block_hash cannot be seen on the chains
[2019-04-05 05:59:30,181][PeerManager:103] INFO [p2p] block Peer(ip='47.102.41.81', port=9996) in PeerManager
[2019-04-05 05:59:30,260][TCPserver:487] INFO [p2p] succeed to send TopBlocksSyncReq to Peer(ip='39.97.166.176', port=9996)
[2019-04-05 05:59:30,265][TCPserver:428] INFO [p2p] received block 00000378d3e8e5e92cee55cfc19c14a3e50ef65f2a94ccdde1d1117d0a8b4be1 from peer Peer(ip='47.111.168.213', port=9996)
[2019-04-05 05:59:30,266][TCPserver:640] INFO [p2p]  block 00000378d3e8e5e92cee55cfc19c14a3e50ef65f2a94ccdde1d1117d0a8b4be1 failed validation as an orphan block
[2019-04-05 05:59:30,344][PeerManager:69] INFO [p2p] Peer(ip='39.97.166.176', port=9996) is already in PeerManager
[2019-04-05 05:59:30,423][PeerManager:69] INFO [p2p] Peer(ip='47.102.41.81', port=9996) is already in PeerManager
[2019-04-05 05:59:30,601][PeerManager:69] INFO [p2p] Peer(ip='161.117.84.146', port=9996) is already in PeerManager
[2019-04-05 05:59:30,633][PeerManager:69] INFO [p2p] Peer(ip='161.117.84.146', port=9996) is already in PeerManager
[2019-04-05 05:59:30,634][PeerManager:69] INFO [p2p] Peer(ip='45.58.54.216', port=9996) is already in PeerManager
[2019-04-05 05:59:30,793][PeerManager:69] INFO [p2p] Peer(ip='47.102.41.81', port=9996) is already in PeerManager
[2019-04-05 05:59:30,844][TCPserver:507] INFO received sync blocks for the orphan block in handleBlockRev, but the first blocks's pre_block_hash cannot be seen on the chains
```
