### ISSUE TITLE
Python版本的upnp在真实网络环境下的测试

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgenceChain#97]
### 背景

+ 局域网内，每个主机都有一个在 *[保留IP字段](https://zh.wikipedia.org/wiki/%E4%BF%9D%E7%95%99IP%E5%9C%B0%E5%9D%80)* （如192或10开头的IP地址）
+ 一个局域网直接管辖的所有主机，可以直接通过IP进行通信。对外，这些主机共用该局域网的路由IP，只是这里的每个主机被分配了路由的不同端口，这一过程叫做*[端口映射](https://blog.csdn.net/songshiMVP1/article/details/51519767)*。可以看出，局域网内的主机不能被拥有公网IP的主机直接访问。

### 目标
实现公网节点向局域网节点建立网络连接并发送数据。

### 条件
已有的公网服务器

### 做为参考的upnp的Python库或例子
+ https://github.com/ZeWaren/python-upnp-ssdp-example
+ https://github.com/fboender/pyupnpclient

**Comment by wolfbrother** [comment]
socket通信的例子，包括客户端和服务器：
### 服务器
```python
from socket import *
 
# 创建socket
tcpSerSocket = socket(AF_INET, SOCK_STREAM)
 
# 绑定本地信息
address = ('', 8999)
tcpSerSocket.bind(address)
 
# 使用socket创建的套接字默认的属性是主动的，使用listen将其变为被动的，这样就可以接收别人的链接了
tcpSerSocket.listen(5)
 
 
# 如果有新的客户端来链接服务器，那么就产生一个信心的套接字专门为这个客户端服务器
# newSocket用来为这个客户端服务
# tcpSerSocket就可以省下来专门等待其他新客户端的链接
newSocket, clientAddr = tcpSerSocket.accept()
 
while True:
 
    # 接收对方发送过来的数据，最大接收1024个字节
    recvData = newSocket.recv(1024)
 
    # 如果接收的数据的长度为0，则意味着客户端关闭了链接
    if len(recvData)<=0:
        break
    else:
        print('recv:',recvData)
 
        # 发送一些数据到客户端
        sendData = input("send:")
        newSocket.send(bytes(sendData.encode("utf8")))
        # 关闭为这个客户端服务的套接字，只要关闭了，就意味着为不能再为这个客户端服务了，如果还需要服务，只能再次重新连接
        newSocket.close()
        break
 
# 关闭监听套接字，只要这个套接字关闭了，就意味着整个程序不能再接收任何新的客户端的连接
tcpSerSocket.close()
```

### 客户端
```python
from socket import *
 
# 创建socket
tcpClientSocket = socket(AF_INET, SOCK_STREAM)
 
# 链接服务器
serAddr = ('127.0.0.1', 8999)
tcpClientSocket.connect(serAddr)
 
while True:
 
    # 提示用户输入数据
    sendData = input("send：")
 
    if len(sendData)>0:
        tcpClientSocket.send(bytes(sendData.encode("utf-8")))
    # 接收对方发送过来的数据，最大接收1024个字节
        recvData = tcpClientSocket.recv(1024)
        print ('recv:',recvData)
        break
    else:
        break
 

 
# 关闭套接字
tcpClientSocket.close()
```

**Comment by piaoliangkb** [comment]
## UPnP(Universal Plug and Play) 通用即插即用

比特币中的NAT采用了upnp，使用开源的miniupnp模块，使用upnp进行NAT穿透的大概过程为：

1. 使用upnp discover方法查找网络中的所有upnp设备

2. 从1中得到的设备列表中找到有效的IGD(Internet Gateway Device)设备，一般为路由器

3. 若2执行成功，则获得IGD的公网ip，ip和程序使用的端口之后将会被广播到P2P网络中

4. 使用upnp portmapping方法进行端口映射，在对应的IGD上添加映射规则，外部网络设备可以访问IGD对应的端口访问局域网内设备

>参考：https://juejin.im/post/5b019ee66fb9a07ac85ab314#heading-6

## python中的upnp模块

- miniupnpc : https://pypi.org/project/miniupnpc/

安装方法(Ubuntu下，Win下anaconda python3.6.8未成功安装)

```
pip3 install miniupnpc
```

设置端口映射方式：

```python
import miniupnpc

upnp = miniupnpc.UPnP()

upnp.discoverdelay = 10
upnp.discover()

upnp.selectigd()

port = 43210

# addportmapping(external-port, protocol, internal-host, internal-port, description, remote-host)
upnp.addportmapping(port, 'TCP', upnp.lanaddr, port, 'testing', '')
```

>参考：https://stackoverflow.com/questions/4391872/python-open-a-listening-port-behind-a-router-upnp/35666064

运行结果：

- 校园网环境下无法发现upnp设备
- 正常router环境下，discover()方法可以发现数个支持upnp的设备，selectigd()方法选择了非网关设备，addportmapping出错（疑问：是否与router未开启upnp有关？）


在github的miniupnp repo中，有两个关于miniupnpc模块的测试例子：

1. https://github.com/miniupnp/miniupnp/blob/miniupnpd_2_1/miniupnpc/pymoduletest3.py

校园网环境下运行结果为

```bash
zl@LAPTOP-ZL:~/upnp/miniupnpc-2.1$ python3 pymoduletest3.py
inital(default) values :
 discoverdelay 0
 lanaddr
 multicastif None
 minissdpdsocket None
Discovering... delay=200ms
0 device(s) detected
Exception : No UPnP device discovered
````


2. https://github.com/miniupnp/miniupnp/blob/miniupnpd_2_1/miniupnpc/testupnpigd.py

校园网环境下运行结果为

```bash
zl@LAPTOP-ZL:~/upnp/miniupnpc-2.1$ python3 testupnpigd.py
Discovering... delay=200ms
0 device(s) detected
Exception : No UPnP device discovered
```

两个测试脚本均无法发现upnp设备

## 其他工具

### 显示局域网中upnp设备信息的脚本

- https://github.com/tenable/upnp_info.git

可显示局域网中upnp设备较为全面的信息，我在实际测试的时候没有发现IGD设备。

### ubuntu系统中的upnpc命令行工具

安装方法为(或者官网下载安装包编译安装，编译过程很简单)：
```bash
apt install miniupnpc
```

对网络中的upnp IGD进行查询：

```bash
zl@LAPTOP-ZL:~/upnp/miniupnpc-2.1$ upnpc -s
upnpc : miniupnpc library test client, version 2.1.
 (c) 2005-2018 Thomas Bernard.
Go to http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/
for more information.
No IGD UPnP Device found on the network !
```

以上结果基于校园网环境；正常环境会列出UPNP设备列表，但是无IGD，推测与路由不支持有关。

### miniupnp开发者issue中提到的Win版本upnptest工具

图形化界面，不需要安装，用于检测网络中不同的upnp设备

issue见：https://github.com/miniupnp/miniupnp/issues/253

工具下载：https://www.majorgeeks.com/files/details/universal_plug_and_play_tester_(upnptest).html

### 以太坊使用的另一个端口映射NAT-PMP

以太坊使用了upnp和NAT-PMP。

原理基本和upnp类似，都需要路由器提供服务。openwrt系统的路由器有开启NAT-PMP的选项。

python对应的库：https://pypi.org/project/NAT-PMP/

源码中相应的一些函数：[https://github.com/jaraco/nat-pmp/blob/1.1/natpmp/init.py](https://github.com/jaraco/nat-pmp/blob/1.1/natpmp/__init__.py)


```bash
>>> from natpmp import *
>>>
>>> get_public_address()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/natpmp/__init__.py", line 265, in get_public_address
    retry=retry, response_size=12)
  File "/usr/local/lib/python3.6/dist-packages/natpmp/__init__.py", line 397, in send_request_with_retry
    NATPMP_GATEWAY_NO_SUPPORT, error_str(NATPMP_GATEWAY_NO_SUPPORT))
natpmp.NATPMPUnsupportedError: (-11, 'The gateway does not support NAT-PMP')
>>> 
>>> map_tcp_port(10000, 10000, 3600)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/natpmp/__init__.py", line 296, in map_tcp_port
    gateway_ip=gateway_ip, retry=retry, use_exception=use_exception)
  File "/usr/local/lib/python3.6/dist-packages/natpmp/__init__.py", line 353, in map_port
    retry=retry)
  File "/usr/local/lib/python3.6/dist-packages/natpmp/__init__.py", line 397, in send_request_with_retry
    NATPMP_GATEWAY_NO_SUPPORT, error_str(NATPMP_GATEWAY_NO_SUPPORT))
natpmp.NATPMPUnsupportedError: (-11, 'The gateway does not support NAT-PMP')
```

执行查询公共ip地址和端口映射的函数时，显示**网关不支持NAT-PMP**错误。

## 综合：

可能因为路由器没开启upnp或者NAT-PMP功能，导致上述结果。

**Comment by piaoliangkb** [comment]
## socket客户端

通过客户端发送心跳包实现长链接。

客户端实现TCP长链接方法和参数说明：

```python
def set_keepalive_linux(sock, after_idle_sec=1, interval_sec=3, max_fails=5):

    """Set TCP keepalive on an open socket.

    It activates after 1 second (after_idle_sec) of idleness,
    then sends a keepalive ping once every 3 seconds (interval_sec),
    and closes the connection after 5 failed ping (max_fails), or 15 seconds

    TCP_KEEPIDLE : The time (in seconds) the connection needs to remain idle
    before TCP starts sending keepalive probes; 每空闲多少秒，就发送keepalive信息

    TCP_KEEPINTVL : The time (in seconds) between individual keepalive probes
    keepalive消息的时间间隔

    TCP_KEEPCNT :  The maximum number of keepalive probes TCP should send
    before dropping the connection; 发送多少个keepalive消息失败之后就关闭连接

    ----------------------------------------------------------------

    上述为Linux系统的参数，通过输入 sysctl -A |grep keepalive 指令，可以得到这些参数的默认值：

    TCP_KEEPINTVL -> net.ipv4.tcp_keepalive_intvl = 75      -- 间隔多少秒发一次嗅探包(75秒)
    TCP_KEEPCNT   -> net.ipv4.tcp_keepalive_probes = 9      -- 嗅探包一共发几次
    TCP_KEEPIDLE  -> net.ipv4.tcp_keepalive_time = 7200     -- TCP连接空闲多少秒后发嗅探包(2小时)

    如果TCP连接2小时（7200秒）内没有数据传输，则发送嗅探包，
    每隔75秒发送一次，共重试9次。9次对方都没响应，则表明此连接已死。

    """ 

    sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)  # 必需，使得socket客户端开启心跳维护
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, after_idle_sec)
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPINTVL, interval_sec)
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPCNT, max_fails)

```

客户端代码：

```python
from socket import *
import time

# 创建socket
tcpClientSocket = socket(AF_INET, SOCK_STREAM)

# 客户端心跳维护
# 长链接在没有数据通信时，定时发送心跳，维持链接状态
# 如果TCP在10秒内没有进行数据传输，则发送嗅探包，
# 每隔3秒发送一次，共发送5次。如果5次都没收到相应，则表示连接已中断。
tcpClientSocket.setsockopt(SOL_SOCKET, SO_KEEPALIVE, 1)
tcpClientSocket.setsockopt(IPPROTO_TCP, TCP_KEEPIDLE, 10)
tcpClientSocket.setsockopt(IPPROTO_TCP, TCP_KEEPINTVL, 3)
tcpClientSocket.setsockopt(IPPROTO_TCP, TCP_KEEPCNT, 5)

# 链接服务器
serAddr = ('127.0.0.1', 28888)
tcpClientSocket.connect(serAddr)

while True:

    localtime = time.asctime(time.localtime(time.time()))
    data = "hello, sending data at {}".format(localtime).encode("utf-8")
    tcpClientSocket.send(data)
    print(data)
    # 间隔较久发送一次数据包
    time.sleep(600)


# 关闭套接字
tcpClientSocket.close()
```

## socket服务端

服务端可以根据具体的需求设置关闭socket的条件，例如多少秒没收到消息则断开。

当前设置为while循环中一直接收消息，并打印出来，保持TCP长链接不断开：

```python
from socket import *

# 创建socket
tcpSerSocket = socket(AF_INET, SOCK_STREAM)

# 绑定本地信息
address = ('', 28888)
tcpSerSocket.bind(address)

# 使用socket创建的套接字默认的属性是主动的，使用listen将其变为被动的，这样就可以接收别人的链接了
tcpSerSocket.listen(5)


# 如果有新的客户端来链接服务器，那么就产生一个信心的套接字专门为这个客户端服务器
# newSocket用来为这个客户端服务
# tcpSerSocket就可以省下来专门等待其他新客户端的链接
newSocket, clientAddr = tcpSerSocket.accept()

while True:

    # 接收对方发送过来的数据，最大接收1024个字节
    recvData = newSocket.recv(1024)

    # 如果接收的数据的长度为0，则意味着客户端关闭了链接
    if len(recvData) <= 0:
        break
    else:
        print('recv:', recvData)

        # # 发送一些数据到客户端
        # sendData = input("send:")
        # newSocket.send(bytes(sendData.encode("utf8")))
        # # 关闭为这个客户端服务的套接字，只要关闭了，就意味着为不能再为这个客户端服务了，如果还需要服务，只能再次重新连接
        # newSocket.close()
        # break


# 关闭监听套接字，只要这个套接字关闭了，就意味着整个程序不能再接收任何新的客户端的连接
tcpSerSocket.close()

```
